### ISSUE TITLE
Indentation sensitive parsing.

### ISSUE THREAD

**Issue by ghost** [ianh/owl#12]
Utterly random question, how difficult do you think it would be to extend owl with indentation sensitive parsing in the style of this paper: https://michaeldadams.org/papers/layout_parsing/LayoutParsing.pdf?

I'm mainly curious since this is a seriously cool project and I've learned a fair bit from it already.  Basically, I'm hoping to absorb your expertise by osmosis. ^_^

**Comment by ianh** [comment]
Hey, thanks for the kind words!  In terms of implementation, Owl is more of a souped-up regular expression engine than a traditional CFG parser, so the techniques from this paper won't work directly.  I think inserting "indent" and "dedent" tokens like [Python's lexer does](https://docs.python.org/3/reference/lexical_analysis.html#indentation) would be a more practical way to go.  You need explicit nesting tokens to support recursion in the grammar anyway.

**Comment by egency** [comment]
I was actually thinking more of something in the vein of symbolic regular expressions.  Say, operating on character/position pairs rather than only characters allowing one to match say "hi", but only if it's some multiple of three characters from the start.  Or maybe one could view "(\n|^)\s*" as a delimiter with a length operation determining the push and pop actions.  In other words effectively using a predicate like "fn(delim,prior-delim){ return delim > prior-delim }" as your push/pop tokens.  Do you think that something like that could work with an architecture similar to Owl's?

**Comment by ianh** [comment]
> In other words effectively using a predicate like "fn(delim,prior-delim){ return delim > prior-delim }" as your push/pop tokens. Do you think that something like that could work with an architecture similar to Owl's?

Yeah, though you need to maintain a stack to handle a situation like:

```
a:
  b:
    c
d
```

where two "pops" need to happen between `c` and `d`.  The algorithm Python uses is detailed [here](https://docs.python.org/3/reference/lexical_analysis.html#indentation):

> Before the first line of the file is read, a single zero is pushed on the stack; this will never be popped off again. The numbers pushed on the stack will always be strictly increasing from bottom to top. At the beginning of each logical line, the line’s indentation level is compared to the top of the stack. If it is equal, nothing happens. If it is larger, it is pushed on the stack, and one INDENT token is generated. If it is smaller, it must be one of the numbers occurring on the stack; all numbers on the stack that are larger are popped off, and for each number popped off a DEDENT token is generated. At the end of the file, a DEDENT token is generated for each number remaining on the stack that is larger than zero.

This is almost possible to do with Owl's already-implemented custom token functions except that there's no way to return multiple tokens (which you have to do when a single newline generates multiple pops).

**Comment by egency** [comment]
Hmm, I have to admit I didn't quite understand the implications of that section until you pointed it out.  I found the section on user defined tokens and it makes quite a bit of sense now.  Owl parser actually seems quite similar to the Pratt parser architecture.

Something somewhat off topic here, can one define juxtaposition operators in Owl?  And if one can, how does that even work?  I've spent a lot of time toying with ways to do it, but all of it seems to come down to rather ugly hacks.

**Comment by ianh** [comment]
> Something somewhat off topic here, can one define juxtaposition operators in Owl?

Sure, you can use the `''` pattern for that:

```
grammar =
   identifier : ident
 .operators infix flat
   '' : juxtaposition
```

[Owl's own grammar](https://github.com/ianh/owl/blob/master/grammar.owl#L31) uses an operator like this to match concatenated patterns in rules.

**Comment by egency** [comment]
Is there a particular reason for using `infix flat` rather than left/right/nonassoc?

**Comment by ianh** [comment]
Not really.  Flat, left, and right match the same strings; it's just the parse tree that's associated differently.  You can experiment with it on this page if you want: https://ianh.github.io/owl/try/#expr

**Comment by egency** [comment]
The visualizations you added are really useful.  I'm going to play with this for a while.  One last question though.  Is there a way to embed Owl in another language?  It seems like it should be possible given the Owl interpreter.

**Comment by ianh** [comment]
Owl isn't designed for embedding as it is, but I do think it would be cool to see an embedded parsing system like it.

**Comment by ianh** [comment]
In particular, I think it could work better than PEG-based embedded parsers for grammars which have balanced begin and end tokens.  PEGs can be hard to understand (see https://jeffreykegler.github.io/Ocean-of-Awareness-blog/individual/2015/03/peg.html), and implementing them efficiently is difficult (most implementations either use backtracking or do [packrat](http://bford.info/pub/lang/packrat-icfp02/)-style memoization which can use a lot of memory).

**Comment by egency** [comment]
That's exactly what I'm hoping for.  Basically all those really annoying parsing tasks that pop up all over the place.  Especially with the Owl interpreter, that's particularly useful since one can basically write up the grammar, try it out to see whether it does what one expects and then run it on the task at hand.  For that matter I should maybe see about finding a regex interpreter for a similar use-case, would be handy.

**Comment by ianh** [comment]
I'm closing this issue since there's nothing directly actionable here.  Feel free to continue the discussion over email if you'd like.
