### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [ianh/owl#15]
I would like to point out that identifiers like “[`_AUTOMATON_H_`](https://github.com/ianh/owl/blob/efb421b987270bf70c9dcf963598757c865fa89e/src/automaton.h#L1 "Update candidate")” and “[`_TERMINAL_H_`](https://github.com/ianh/owl/blob/361a7ec704f6a2ec690d5b06191d4faa3bb26e85/src/terminal.h#L1 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by ianh** [comment]
That's true.  I'm not sure what to do about names like `_2_BUILD_H_` though -- `2_BUILD_H` isn't going to work.

**Comment by elfring** [comment]
I suggest to use another prefix for these include guards.

**Comment by ianh** [comment]
Should be resolved in 7ada0bd.  Thanks for the report!

**Comment by elfring** [comment]
Thanks for [your adjustment of affected include guards](https://github.com/ianh/owl/commit/7ada0bd39488c600148ba1b120ea991fd11d07d8 "Don't use reserved identifiers for include guards.").
