### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [ianh/owl#16]
Would you like to add more error handling for return values from functions like the following?
- [fwrite](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fwrite.html "Binary output") ⇒ [write_to_output](https://github.com/ianh/owl/blob/129b502ce3c0f14c0c3d43a20942376512eff059/src/owl.c#L392)
- [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [main](https://github.com/ianh/owl/blob/129b502ce3c0f14c0c3d43a20942376512eff059/src/owl.c#L130)

**Comment by ianh** [comment]
The return value of `malloc` is already checked anywhere the src/alloc.h header is included (see [src/alloc.h:37](https://github.com/ianh/owl/blob/129b502ce3c0f14c0c3d43a20942376512eff059/src/alloc.h#L37)).  I might as well add a similar check to the call to fwrite.

**Comment by ianh** [comment]
Added in ce800c8.

**Comment by ianh** [comment]
There are other calls to `fwrite`, but they should just be going to stdout/stderr.  I'm not sure detecting errors there is worthwhile.

**Comment by elfring** [comment]
>The return value of malloc is already checked

Would it be clearer to use your own function names directly instead of the applied renaming?

-----

I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by ianh** [comment]
It may be slightly clearer, but I think it also makes the code harder to read.  I only added those checks because of the WebAssembly target, where `malloc` failure actually happens somewhat frequently.

**Comment by elfring** [comment]
[A few update candidates were left over](https://github.com/ianh/owl/blob/129b502ce3c0f14c0c3d43a20942376512eff059/src/owl.c#L63 "Update candidate: main()").
