### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [ianh/owl#17]
I suggest to reuse a higher level build system than [your current make script](https://github.com/ianh/owl/blob/4c7ee00093d770fe4cab7b4faa21c76189cc2545/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
- [CMake](https://cmake.org/ "Building software with CMake")
- [Autotools](https://www.gnu.org/software/autoconf/autoconf.html#introduction "Building software with Autoconf")

**Comment by ianh** [comment]
Sorry, I'm not going to change the build system without a very strong justification.

Can I ask what you're using Owl for that you need all these changes?

**Comment by elfring** [comment]
- Does [a tool like “autoscan”](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
- How do you think about to support more development environments by [the reuse of build system generators](https://cmake.org/cmake/help/v3.16/manual/cmake-generators.7.html#cmake-generators "Listing of CMake generators")?
