### ISSUE TITLE
Other types of numbers?

### ISSUE THREAD

**Issue by WarrenWeckesser** [ianh/owl#2]
`owl` is fantastic, thanks for sharing it!  I've started experimenting with  it for creating a little language that defines a system of differential equations.

The predefined `number` is convenient, but I would like to have more flexible parsing of numbers.  In some expressions, I want integers only.  For example, in parsing the expression in an index operation such as `x[k - 1]`, the numerical values inside the brackets must be integers.  I want to treat `x[k - 1.5]` as invalid.

For other expressions, I would like to parse complex numbers, where the imaginary part of the number is indicated with a `j`, e.g. `z = -1.0 + 2.5j` (I'm using the Python convention for complex numbers).

Is there already an obvious way to handle these cases, or will I have to modify the tokenizer to not automatically consume numerical values as doubles?  After only a brief look at the code, I suspect modifying the tokenizer would involve adding two more numerical token types, say `integer` and `imaginary`.  If the sequence of characters in the input stream contains a number that is terminated by `j` (with no whitespace), create an `imaginary` token, and if the number is only digits (and not terminated by `j`), create an `integer`.

**Comment by ianh** [comment]
Thanks for the bug report!  The code doesn't make it particularly easy to add new kinds of tokens right now—sorry about that.

One solution I'm considering is to allow custom token types in the grammar, then have a callback your code can use to recognize those tokens itself.  Something like:

```
.tokens integer imaginary
```

Which would generate `TOKEN_INTEGER` and `TOKEN_IMAGINARY` enum values.  Then you would define an `owl_tokenize_callback` function:

```
enum token_type owl_tokenize_callback(...) {
    if (/* it's an integer */)
        return TOKEN_INTEGER;
    // and so on...
}
```

Does this seem like a workable solution?  The other route would be to define the token patterns as regular expressions in the grammar itself, but that's a much bigger project…

**Comment by WarrenWeckesser** [comment]
> Thanks for the bug report!

Bug report? Nah, this is an enhancement request!

Your suggestion sounds reasonable.  Would the callback become an argument to the `ow_tree_create_from_*` functions?

**Comment by ianh** [comment]
Yeah, or a new `owl_tree_create(...)` function which takes an options struct (for possible future extensibility, and so anyone not using a custom tokenizer doesn't have to think about it).

**Comment by ianh** [comment]
I just pushed some changes to add support for user-defined token types.  There's documentation at https://github.com/ianh/owl/blob/master/doc/grammar-reference.md#user-defined-tokens and https://github.com/ianh/owl/blob/master/doc/generated-parser.md#user-defined-tokens — let me know if you have any feedback!

**Comment by ianh** [comment]
A new version has been released with custom token support, which should address this issue.  Feel free to open new issues for any feedback you have.
