### ISSUE TITLE
Parser doesn't compile with multiple custom tokens

### ISSUE THREAD

**Issue by numist** [ianh/owl#21]
The grammar:

```
.token foo
.token bar

program = 'f'
```

Produces a parser.h that fails to compile due to defining one `write_custom_token` function for each custom token:

``` c
static void write_custom_token(size_t offset, size_t length, uint32_t token, uint64_t data, void *info) {
    struct owl_tree *tree = info;
    size_t token_offset = tree->next_offset;
    write_tree(tree, token_offset - tree->next_foo_token_offset);
    write_tree(tree, offset);
    write_tree(tree, length);
    write_tree(tree, data);
    tree->next_foo_token_offset = token_offset;
}
static void write_custom_token(size_t offset, size_t length, uint32_t token, uint64_t data, void *info) { // <== Redefinition of write_custom_token
    struct owl_tree *tree = info;
    size_t token_offset = tree->next_offset;
    write_tree(tree, token_offset - tree->next_bar_token_offset);
    write_tree(tree, offset);
    write_tree(tree, length);
    write_tree(tree, data);
    tree->next_bar_token_offset = token_offset;
}
```

**Comment by ianh** [comment]
Thanks for the report!  This should be fixed in 8468ba9.

**Comment by ianh** [comment]
By the way, I wouldn't be surprised if there were more bugs in code generation… I spent a while fuzzing the interpreter (this is where the `-T` option came from) but never set up an end-to-end test for compilation.

**Comment by ianh** [comment]
So, I got motivated to do this… 0ec2373 adds an `owl -T -c` end-to-end compilation test mode.  I also converted all the tests to .owltest format (something I'd been meaning to do for a while) as part of this work.

**Comment by numist** [comment]
![tumblr_p70j84hKEr1t0gmsbo7_500](https://user-images.githubusercontent.com/544011/102642266-494e0a00-4112-11eb-8fb0-86a1ccea634b.jpg)

Verified fixed, thanks!
