### ISSUE TITLE
Potential crash after calloc due to empty node->slots

### ISSUE THREAD

**Issue by falkoschindler** [ianh/owl#26]
In `construct_node_alloc()` there is a possibly empty allocation, because `number_of_slots` can be 0:

https://github.com/ianh/owl/blob/b7f1cf43ec09201fe5c460f398badaa45d2626b2/src/1-parse.h#L1675-L1676

In this case the behavior of `calloc()` is not defined:

> If nmemb or size is 0, then calloc() returns either NULL, or a unique pointer value that can later be successfully passed to free().
https://linux.die.net/man/3/calloc

I was trying to compile owl for an embedded system, but `abort()` was called when creating the tree. So I fixed the parser with the following sed command, considering the number of slots within the if-statement:

```
sed -i '' 's/(!node->slots)/(number_of_slots \&\& !node->slots)/' src/parser.h
```

I guess a similar fix would help to ensure a more consistent behavior across different compilers/architectures.

**Comment by ianh** [comment]
Ah, nice catch!  Fixed in e661392 and ca629ee.
