### ISSUE TITLE
Out-of-bounds Read Vulnerability

### ISSUE THREAD

**Issue by circeanubogdan** [ianh/owl#33]
Hello,

I am currentlry working on [OpenCRS](https://github.com/orgs/CyberReasoningSystem/repositories?type=all), and I used your app for testing the Vulnerability Detection module.

While doing so, I discovered an out-of-bounds read that could prove itself as a vulnerability.

### Steps to reproduce

1. Compile using the base Makefile.
2. Run with valgrind to see the error report for the invalid read: `valgrind ./owl -T -g -`.

### Patches
I already forked the repository and proposed a patch in the Pull Request #32

**Comment by ianh** [comment]
Fixed in 93a6b7c -- thanks for the report.
